#! /bin/bash
set -ex

main ()
{
    if [[ "$WG_ADDRESS" == "" ]]; then
	echo 'need address'
	exit 1
    fi
    ip link del dev wg0  2>/dev/null || true
    ip link add dev wg0 type wireguard
    ip addr add dev wg0 $WG_ADDRESS
    ip link set up dev wg0
    wg setconf wg0 /etc/wireguard/wg0/test.conf
    if [ "$1" == "default-route" ]; then
	host="$(wg show wg0 endpoints | sed -n 's/.*\t\(.*\):.*/\1/p')"
	ip route add $(ip route get $host | sed '/ via [0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/{s/^\(.* via [0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*/\1/}' | head -n 1) 2>/dev/null || true
	ip route add 0/1 dev wg0
	ip route add 128/1 dev wg0
	echo -e "nameserver 1.1.1.1\\nnameserver 1.0.0.1" |tee /etc/resolv.conf
    fi
}

main "$@"
