# ansible/build/lib.linux-x86_64-2.7/ansible/modules/packaging/os/
---
- hosts: all
  become: true
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: true
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        force_apt_get: true
